# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a31cac0b3770e08e5158e9159956e5a2cbba8193eaa8e7d0f02568ab2f27e815a15538326a93b5d85bb2b3b8fed5745c90d1306c0cd379fa1527cce9e7a4ebd

test:
  secret_key_base: 7e91627c528ff91dfbeda189ce02427571c022ee79f1be02ba4607d4bc2d9cda6462b0285cfd2ea5603999a1f831bb02e6fe6e5175d741f5ef7ea77c916da8ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
